unbind C-b
set -g prefix C-a
bind C-a send-prefix
set -g mouse on
set -g default-terminal "tmux-256color"
set -as terminal-overrides ",*256col*:RGB"
set -g mode-keys vi
set -g base-index 1
set -g pane-base-index 1
set -g status off

set -g renumber-windows on

bind c new-window -c "#{pane_current_path}"
bind '"' split-window -h   -c "#{pane_current_path}"
bind '%' split-window -v -l 20% -c "#{pane_current_path}"

bind r source-file ~/.config/tmux/tmux.conf

set -g @resurrect-save 'S'
set -g @resurrect-restore 'R'

bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

bind C-h set-option status

# Plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-yank'
set -g @plugin 'tmux-plugins/tmux-resurrect'

run '~/.config/tmux/plugins/tpm/tpm'
