# General settings
set -g default-terminal "tmux-256color"
set -g base-index 1
set -g status-position top
set -g pane-base-index 1
set -g prefix C-b
bind C-b send-prefix
set-option -g focus-events on
set -g extended-keys on
set -g mouse on
set -g history-limit 50000

set -g @vim_navigator_mapping_left "C-Left C-h"
set -g @vim_navigator_mapping_right "C-Right C-l"
set -g @vim_navigator_mapping_up "C-k"
set -g @vim_navigator_mapping_down "C-j"
set -g @vim_navigator_mapping_prev ""

bind -r H resize-pane -L 5
bind -r J resize-pane -D 5
bind -r K resize-pane -U 5
bind -r L resize-pane -R 5

# Copy/scroll keybinds
bind -T copy-mode-vi v send-keys -X begin-selection
bind -T copy-mode-vi C-v send-keys -X rectangle-toggle
bind -T copy-mode-vi y send-keys -X copy-selection-and-cancel
bind -n PageUp copy-mode -u

# Set behavior for creating panes and windows at cur path
bind '"' split-window -c "#{pane_current_path}"
bind % split-window -h -c "#{pane_current_path}"
bind c new-window -c "#{pane_current_path}"

# Utility keybinds
bind F1 set-option -g status
bind r source-file ~/.config/tmux/tmux.conf

# Visual settings
set -g @tokyo-night-tmux_theme night
set -g @tokyo-night-tmux_transparent 1
set -g @tokyo-night-tmux_show_git 1
set -g @tokyo-night-tmux_window_id_style hide
set -g @tokyo-night-tmux_pane_id_style hsquare
set -g @tokyo-night-tmux_zoom_id_style none

# Plug & something
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-yank'
set -g @plugin 'christoomey/vim-tmux-navigator'
set -g @plugin "janoamaral/tokyo-night-tmux"


run '~/.tmux/plugins/tpm/tpm'
