#!/bin/bash
# Tokyo Night "night" palette, colors as 0xAARRGGBB.
#   active   blue #7aa2f7 -> purple #bb9af7 gradient
#   inactive fg_gutter #3b4261

options=(
  style=round
  width=2.0
  hidpi=on
  active_color="gradient(top_left=0xee7aa2f7,bottom_right=0xeebb9af7)"
  inactive_color=0xaa3b4261
  background_color=0x00000000
)

borders "${options[@]}"
