#!/bin/bash
# Tokyo Night "night" palette, colors as 0xAARRGGBB.
#   active   blue #7aa2f7 -> purple #bb9af7 gradient
#   inactive fg_gutter #3b4261

options=(
  style=round
  width=6.0
  hidpi=off
  active_color="gradient(top_left=0xff7aa2f7,bottom_right=0xffbb9af7)"
  inactive_color=0xff3b4261
  background_color=0x00000000
)

borders "${options[@]}"
